# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.dmc.ajou.ac.kr:
  peer0.org1.dmc.ajou.ac.kr:
  peer1.org1.dmc.ajou.ac.kr:
<<<<<<< HEAD
  peer0.org2.dmc.ajou.ac.kr:
  peer1.org2.dmc.ajou.ac.kr:
  peer0.org3.dmc.ajou.ac.kr:
  peer1.org3.dmc.ajou.ac.kr:  
=======
  peer2.org1.dmc.ajou.ac.kr:
  peer0.org2.dmc.ajou.ac.kr:
  peer0.org3.dmc.ajou.ac.kr:
>>>>>>> 210ac451f2a4986a7b9007d176f467367c688afb

networks:
  byfn:

services:

  orderer.dmc.ajou.ac.kr:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.dmc.ajou.ac.kr
    container_name: orderer.dmc.ajou.ac.kr
    networks:
      - byfn

  peer0.org1.dmc.ajou.ac.kr:
    container_name: peer0.org1.dmc.ajou.ac.kr
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.dmc.ajou.ac.kr
    networks:
      - byfn

  peer1.org1.dmc.ajou.ac.kr:
    container_name: peer1.org1.dmc.ajou.ac.kr
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.dmc.ajou.ac.kr
    networks:
      - byfn

<<<<<<< HEAD
  peer0.org2.dmc.ajou.ac.kr:
    container_name: peer0.org2.dmc.ajou.ac.kr
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.dmc.ajou.ac.kr
    networks:
      - byfn

  peer1.org2.dmc.ajou.ac.kr:
    container_name: peer1.org2.dmc.ajou.ac.kr
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org2.dmc.ajou.ac.kr
=======
  peer2.org1.dmc.ajou.ac.kr:
    container_name: peer2.org1.dmc.ajou.ac.kr
    extends:
      file:  base/docker-compose-base.yaml
      service: peer2.org1.dmc.ajou.ac.kr
    networks:
      - byfn

  peer0.org2.dmc.ajou.ac.kr:
    container_name: peer0.org2.dmc.ajou.ac.kr
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.dmc.ajou.ac.kr
>>>>>>> 210ac451f2a4986a7b9007d176f467367c688afb
    networks:
      - byfn

  peer0.org3.dmc.ajou.ac.kr:
    container_name: peer0.org3.dmc.ajou.ac.kr
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org3.dmc.ajou.ac.kr
<<<<<<< HEAD
    networks:
      - byfn

  peer1.org3.dmc.ajou.ac.kr:
    container_name: peer1.org3.dmc.ajou.ac.kr
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org3.dmc.ajou.ac.kr
=======
>>>>>>> 210ac451f2a4986a7b9007d176f467367c688afb
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.dmc.ajou.ac.kr:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.dmc.ajou.ac.kr/peers/peer0.org1.dmc.ajou.ac.kr/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.dmc.ajou.ac.kr/peers/peer0.org1.dmc.ajou.ac.kr/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.dmc.ajou.ac.kr/peers/peer0.org1.dmc.ajou.ac.kr/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.dmc.ajou.ac.kr/users/Admin@org1.dmc.ajou.ac.kr/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.dmc.ajou.ac.kr
      - peer0.org1.dmc.ajou.ac.kr
      - peer1.org1.dmc.ajou.ac.kr
<<<<<<< HEAD
      - peer0.org2.dmc.ajou.ac.kr
      - peer1.org2.dmc.ajou.ac.kr
      - peer0.org3.dmc.ajou.ac.kr
      - peer1.org3.dmc.ajou.ac.kr
=======
      - peer2.org1.dmc.ajou.ac.kr
      - peer0.org2.dmc.ajou.ac.kr
      - peer0.org3.dmc.ajou.ac.kr
>>>>>>> 210ac451f2a4986a7b9007d176f467367c688afb
    networks:
      - byfn
