# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.dmc.ajou.ac.kr:
  peer0.org1.dmc.ajou.ac.kr:
  peer1.org1.dmc.ajou.ac.kr:
<<<<<<< HEAD
  peer0.org2.dmc.ajou.ac.kr:
  peer1.org2.dmc.ajou.ac.kr:
  peer0.org3.dmc.ajou.ac.kr:
  peer1.org3.dmc.ajou.ac.kr:
=======
  peer2.org1.dmc.ajou.ac.kr:
  peer0.org2.dmc.ajou.ac.kr:
  peer0.org3.dmc.ajou.ac.kr:
>>>>>>> 210ac451f2a4986a7b9007d176f467367c688afb

networks:
  byfn:
services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.dmc.ajou.ac.kr-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.dmc.ajou.ac.kr-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.dmc.ajou.ac.kr/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1
    networks:
      - byfn

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.dmc.ajou.ac.kr-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.dmc.ajou.ac.kr-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.dmc.ajou.ac.kr/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg2
    networks:
      - byfn
  
  ca2:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org3
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org3.dmc.ajou.ac.kr-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA3_PRIVATE_KEY
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org3.dmc.ajou.ac.kr-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA3_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org3.dmc.ajou.ac.kr/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg3
    networks:
      - byfn

<<<<<<< HEAD
=======
  ca2:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org3
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org3.dmc.ajou.ac.kr-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA3_PRIVATE_KEY
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org3.dmc.ajou.ac.kr-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA3_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org3.dmc.ajou.ac.kr/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg3
    networks:
      - byfn

>>>>>>> 210ac451f2a4986a7b9007d176f467367c688afb
  orderer.dmc.ajou.ac.kr:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.dmc.ajou.ac.kr
    container_name: orderer.dmc.ajou.ac.kr
    networks:
      - byfn

  peer0.org1.dmc.ajou.ac.kr:
    container_name: peer0.org1.dmc.ajou.ac.kr
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.dmc.ajou.ac.kr
<<<<<<< HEAD
    networks:
      - byfn

  peer1.org1.dmc.ajou.ac.kr:
    container_name: peer1.org1.dmc.ajou.ac.kr
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.dmc.ajou.ac.kr
    networks:
      - byfn

  peer0.org2.dmc.ajou.ac.kr:
    container_name: peer0.org2.dmc.ajou.ac.kr
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.dmc.ajou.ac.kr
    networks:
      - byfn

  peer1.org2.dmc.ajou.ac.kr:
    container_name: peer1.org2.dmc.ajou.ac.kr
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org2.dmc.ajou.ac.kr
    networks:
      - byfn

  peer0.org3.dmc.ajou.ac.kr:
    container_name: peer0.org3.dmc.ajou.ac.kr
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org3.dmc.ajou.ac.kr
    networks:
      - byfn

  peer1.org3.dmc.ajou.ac.kr:
    container_name: peer1.org3.dmc.ajou.ac.kr
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org3.dmc.ajou.ac.kr
=======
    networks:
      - byfn

  peer1.org1.dmc.ajou.ac.kr:
    container_name: peer1.org1.dmc.ajou.ac.kr
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.dmc.ajou.ac.kr
    networks:
      - byfn

  peer2.org1.dmc.ajou.ac.kr:
    container_name: peer2.org1.dmc.ajou.ac.kr
    extends:
      file:  base/docker-compose-base.yaml
      service: peer2.org1.dmc.ajou.ac.kr
    networks:
      - byfn

  peer0.org2.dmc.ajou.ac.kr:
    container_name: peer0.org2.dmc.ajou.ac.kr
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.dmc.ajou.ac.kr
    networks:
      - byfn

  peer0.org3.dmc.ajou.ac.kr:
    container_name: peer0.org3.dmc.ajou.ac.kr
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org3.dmc.ajou.ac.kr
>>>>>>> 210ac451f2a4986a7b9007d176f467367c688afb
    networks:
      - byfn
